# Generated by Django 3.0.4 on 2020-07-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=400)),
                ('subject', models.CharField(max_length=400)),
                ('message', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(default=None, verbose_name='date published')),
            ],
        ),
        migrations.RenameModel(
            old_name='HomeOwner',
            new_name='Notification',
        ),
    ]
